lengthn=2;                   %number of parameters
n=1;                         %number before decimal
N=20;                        %number of runs
maxperc=20;                  %number after decimal
mutrate=5e-1;                %mutation rate
fitnessthreshold=.1;          %will stop if fitness below threshhold
thresholdruns=5;             %will start new era if more than this many runs with no changes
survival=round(.25*N);       %number of surviving parents
improvethresh=10000;         %will end if no improvents in this time 
chromosomes=chromgen(lengthn,N,maxperc,n); %generates chromosomes
count=1                      %counter for loops of G.A
under=0;                     %number of times with no change
Reset=0;                     %will start new era if is equal to 1
era=1                        %era number
noimprove=0;                 %number of generations since last improvement in fitness